inputs:
  appleAPIKey:
    description: 'The App Store Connect API key, if using JWT authentication to notarize your app.'
    required: false
  appleAPIIssuer:
    description: 'The App Store Connect Issuer ID. Required if appleAPIKey is set.'
    required: false
  appleID:
    description: 'The username for your Apple Developer account.'
    required: false
  appleIDPassword:
    description: 'The app-specific password for your Apple Developer account.'
    required: false
  macos-cert-importer:
    description: 'Path to script used to import the macOS P12 certificate used to sign the app.'
    default: '$GITHUB_ACTION_PATH/scripts/import-macos-cert.sh'
    required: false
  macos-cert-p12:
    description: 'The base64-encoded contents of the macOS P12 certificate used to sign the app. Used by the default `macos-cert-importer` script.'
    required: false
  macos-cert-password:
    description: 'The password used to unlock the signing certificate so that it can be imported into the keychain.'
    required: false
  node-installer:
    description: 'Which Node.js package manager to use (`yarn` or `npm`). Defaults to detecting which package manager was used on the app via `yarn-or-npm` (which is used by Electron Forge).'
    required: false
  target-arch:
    description: 'The target architecture for the bundled Electron app. Defaults to the architecture of the host runner.'
    required: false
  target-platform:
    description: 'The target platform for the bundled Electron app.'
    required: true

runs:
  using: composite
  steps:
    - name: Set up macOS signing certificate
      shell: bash
      run: ${{ inputs.macos-cert-importer }}
      env:
        MACOS_CERT_PASSWORD: ${{ inputs.macos-cert-password }}
        MACOS_CERT_P12: ${{ inputs.macos-cert-p12 }}
    - name: Install
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/install.sh
    - name: Bundle app
      shell: bash
      run: $GITHUB_ACTION_PATH/scripts/package.sh
      env:
        APPLE_API_KEY: ${{ inputs.appleAPIKey }}
        APPLE_API_ISSUER: ${{ inputs.appleAPIIssuer }}
        APPLE_ID: ${{ inputs.appleID }}
        APPLE_ID_PASSWORD: ${{ inputs.appleIDPassword }}
        NODE_INSTALLER: ${{ inputs.node-installer }}
        TARGET_ARCH: ${{ inputs.target-arch }}
        TARGET_PLATFORM: ${{ inputs.target-platform }}
